[project]
name = "mentoring"
version = "0.1.0"
description = "Mentor helper for Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.0.1",
    "ipython>=9.6.0",
    "ruff>=0.14.2",
]
